/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/skull/scene.gltf -r public 
Author: BlockedGravity (https://sketchfab.com/blockedgravity)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/little-planet-earth-d54bb387f62147dcbf4be0605068b1cc
Title: Little Planet Earth
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/skull/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Clouds_2_Clouds_1.geometry} material={materials.Clouds} position={[0, 0, -500]} />
      <mesh geometry={nodes.Ocean_Mat_0.geometry} material={materials.material} position={[0, 0, -500]} />
      <mesh geometry={nodes.CONT_Extrude_Mat3_0.geometry} material={materials['Mat.3']} position={[-64.303, 10.837, -5]} />
      <mesh geometry={nodes.SP_Extrude_Ice_0.geometry} material={materials.material_3} position={[0, 500, -500]} />
      <mesh geometry={nodes.NP_Extrude_Ice_0.geometry} material={materials.material_3} position={[0, -500, -500]} />
    </group>
  )
}

useGLTF.preload('/skull/scene.gltf')
