/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 public/skull/scene.gltf -r public 
Author: Sergey Egelsky (https://sketchfab.com/egelsky)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/human-skull-b0251e48e906418ebae34b7f811ca065
Title: Human Skull
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/skull/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.DefaultMaterial} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.DefaultMaterial} />
          <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.DefaultMaterial} />
          <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.DefaultMaterial} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/skull/scene.gltf')
